-- we can read Lua syntax here!
return {
    ["font_embolden"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_t_page_margin"] = 15,
    ["doc_pages"] = 1130,
    ["font_kerning"] = 3,
    ["copt_render_dpi"] = 96,
    ["copt_space_condensing"] = 75,
    ["highlight_drawer"] = "lighten",
    ["bookmarks"] = {},
    ["copt_visible_pages"] = 1,
    ["font_size"] = 22,
    ["render_mode"] = 0,
    ["screen_mode"] = "portrait",
    ["render_dpi"] = 96,
    ["inverse_reading_order"] = false,
    ["nightmode_images"] = true,
    ["cache_file_path"] = "/storage/emulated/0/koreader/cache/cr3cache/Karl-May-Dur-d-Harem.epub.e9311437.1.cr3",
    ["copt_font_kerning"] = 3,
    ["last_xpointer"] = "/body/DocFragment[1]/body/div[1]/text()[14].0",
    ["copt_nightmode_images"] = 1,
    ["header_font_face"] = "Noto Sans",
    ["stats"] = {
        ["performance_in_pages"] = {},
        ["md5"] = "7367ccadec7caa0e1dcf12d108305849",
        ["authors"] = "Karl May",
        ["total_time_in_sec"] = 0,
        ["notes"] = 0,
        ["title"] = "Durch Wüste und Harem / Gesammelte Reiseromane, Band I",
        ["highlights"] = 0,
        ["pages"] = 1130,
        ["series"] = "",
        ["language"] = "de"
    },
    ["doc_props"] = {
        ["title"] = "Durch Wüste und Harem / Gesammelte Reiseromane, Band I",
        ["keywords"] = "Adventure stories\
Middle East -- Fiction\
German fiction",
        ["description"] = "",
        ["authors"] = "Karl May",
        ["series"] = "",
        ["language"] = "de"
    },
    ["font_hinting"] = 2,
    ["gamma_index"] = 15,
    ["copt_smooth_scaling"] = 0,
    ["highlights_imported"] = true,
    ["line_space_percent"] = 100,
    ["copt_sync_t_b_page_margins"] = 0,
    ["space_condensing"] = 75,
    ["floating_punctuation"] = 0,
    ["copt_screen_mode"] = "portrait",
    ["font_face"] = "Noto Serif",
    ["embedded_fonts"] = true,
    ["copt_font_weight"] = 0,
    ["copt_status_line"] = 1,
    ["visible_pages"] = 1,
    ["copt_block_rendering_mode"] = 3,
    ["readermenu_tab_index"] = 1,
    ["percent_finished"] = 0.0017699115044248,
    ["disable_fuzzy_search"] = false,
    ["partial_md5_checksum"] = "bd9cc3ad5311173dd0d4028d2c295fc0",
    ["highlight"] = {},
    ["rotation_mode"] = 0,
    ["copt_embedded_fonts"] = 1,
    ["config_panel_index"] = 1,
    ["embedded_css"] = true,
    ["smooth_scaling"] = false,
    ["copt_b_page_margin"] = 15,
    ["copt_line_spacing"] = 100,
    ["copt_font_size"] = 22,
    ["highlight_disabled"] = false,
    ["copt_embedded_css"] = 1,
    ["copt_h_page_margins"] = {
        [1] = 20,
        [2] = 20
    },
    ["page_overlap_style"] = "dim",
    ["copt_view_mode"] = 0,
    ["css"] = "./data/epub.css",
    ["copt_font_hinting"] = 2,
    ["cre_dom_version"] = 20180528,
    ["show_overlap_enable"] = false,
    ["gamma"] = 1,
    ["bookmarks_sorted"] = true
}
