name: Publish JavaDoc

on:
  push:
    branches: master
    paths:
    - '**.java'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8

      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Create JavaDoc documentation
      run: |
        mkdir web
        javadoc -package -notree -nonavbar -noindex -d web/docs $(find src/main/java -name *.java) -classpath /usr/local/lib/android/sdk/platforms/android-29/android.jar
        cp README.md web
        hash=$(git log -1 --format=%H)
        shortHash=$(git log -1 --format=%h)
        sed -i -E 's/(<\/ul>)/\1\n<p>Repository: <a href="https:\/\/github.com\/mahlzahn\/koreaderhistfavparser" title="GitHub repository of KOReaderHistFavParser" target="_blank">koreaderhistfavparser<\/a><br>\nVersion: <a href="https:\/\/github.com\/mahlzahn\/koreaderhistfavparser\/commit\/'$hash'" title="Commit '$shortHash' on GitHub" target="_blank">'$shortHash'<\/a><\/p>/' web/docs/allclasses-frame.html

    - name: Deploy changes to gh-pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./web

